const { ethers } = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
  console.log("Deploying CertificateRegistry...");

  const [deployer] = await ethers.getSigners();
  console.log(`Deploying with account: ${deployer.address}`);

  const CertificateRegistry = await ethers.getContractFactory("CertificateRegistry");
  const registry = await CertificateRegistry.deploy();
  await registry.waitForDeployment();

  const address = await registry.getAddress();
  console.log(`CertificateRegistry deployed at: ${address}`);

  // Extract ABI from compiled artifacts
  const artifactPath = path.join(
    __dirname,
    "../artifacts/contracts/CertificateRegistry.sol/CertificateRegistry.json"
  );
  const artifact = JSON.parse(fs.readFileSync(artifactPath, "utf8"));

  // Write config.js so the frontend can import address + ABI
  const configDir = path.join(__dirname, "../src/contract");
  if (!fs.existsSync(configDir)) {
    fs.mkdirSync(configDir, { recursive: true });
  }

  const configContent = `// Auto-generated by scripts/deploy.js — do not edit manually
export const CONTRACT_ADDRESS = "${address}";

export const CONTRACT_ABI = ${JSON.stringify(artifact.abi, null, 2)};
`;

  fs.writeFileSync(path.join(configDir, "config.js"), configContent, "utf8");
  console.log("Saved contract address and ABI to src/contract/config.js");
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
